In [3]:
import pandas as pd

df_puntos_med= pd.read_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\wifi_puntos_medellin_comuna.csv", encoding="utf-8", sep =",")

In [4]:
df_puntos_med.head()

     comuna   barrio                                               sede
0  Comuna 1  Popular                                Parque de Guadalupe
1  Comuna 1  Popular                          Unidad Deportiva Granizal
2  Comuna 1  Popular  Plazoleta Entre I.E. Antonio Derka y la I.E. S...
3  Comuna 1  Popular                 CVS Popular (CEDEZO Santo Domingo)
4  Comuna 1  Popular  Plazoleta Estación Metrocable Popular 1 (exter...

In [ ]:
# Cambiar el tipo de dato de la columna comuna a entero, eliminando el texto "Comuna " y dejando solo el número de la comuna
df_puntos_med["comuna"] = df_puntos_med["comuna"].str.split().str[1].astype(int)

   comuna   barrio                                               sede
0       1  Popular                                Parque de Guadalupe
1       1  Popular                          Unidad Deportiva Granizal
2       1  Popular  Plazoleta Entre I.E. Antonio Derka y la I.E. S...
3       1  Popular                 CVS Popular (CEDEZO Santo Domingo)
4       1  Popular  Plazoleta Estación Metrocable Popular 1 (exter...

In [14]:
df_puntos_med.to_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\wifi_puntos_medellin_comuna.csv", index=False, encoding="utf-8", sep =",")