In [8]:
import pandas as pd

df_segmentacion = pd.read_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\segmentacion_de_usuarios.csv", encoding="utf-8", sep =",")

In [9]:
df_segmentacion.head()

,Sedes,Autenticación_Correo,Autenticación_Facebook,Autenticación_Googleplus,Autenticación_Linkedin,Autenticación_Twitter,Rango_edad_desconocido,Rango_edad_De_14_a_17_Años,Rango_edad_De_18_a_28_Años,Rango_edad_De_29_a_50_Años,...,Rango_edad_Menor_de_13_Años,Dispositivo_conexión_Computadora_personal,Dispositivo_conexión_Smartphone,Dispositivo_conexión_Tablet,Género_desconocido,Sexo_Femenino,Sexo_Masculino,Género_Otro,Mes,Año
0,Aeroparque Juan Pablo Segundo,6762,450,51,0,4,5554,183,924,543,...,10,124,6988,155,5320,835,1097,15,Julio,2018.0
1,Ampliación 1 Estación Caribe (Norte),6776,200,5,0,0,5402,137,884,511,...,11,242,6696,43,5352,693,915,21,Julio,2018.0
2,Ampliación 2 Estación Caribe (Sur),6044,225,20,0,2,5108,111,669,347,...,18,55,6204,32,5002,478,798,13,Julio,2018.0
3,Ampliación Estación Estadio,19760,768,17,0,5,16676,350,2126,1260,...,41,178,20265,107,16284,1626,2601,39,Julio,2018.0
4,Ampliación La Honda,9555,424,15,0,5,7886,313,1251,474,...,27,123,9791,85,7781,977,1216,25,Julio,2018.0

In [10]:
df_segmentacion.info()

<class 'pandas.DataFrame'>
RangeIndex: 2650 entries, 0 to 2649
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Sedes                                      2650 non-null   str
 1   Autenticación_Correo                       2650 non-null   int64
 2   Autenticación_Facebook                     2650 non-null   int64
 3   Autenticación_Googleplus                   2650 non-null   int64
 4   Autenticación_Linkedin                     2650 non-null   int64
 5   Autenticación_Twitter                      2650 non-null   int64
 6   Rango_edad_desconocido                     2650 non-null   int64
 7   Rango_edad_De_14_a_17_Años                 2650 non-null   int64
 8   Rango_edad_De_18_a_28_Años                 2650 non-null   int64
 9   Rango_edad_De_29_a_50_Años                 2650 non-null   int64
 10  Rango_edad_Mayor_de_50_Años                2650 non-null   int64
 11  Rango_edad_Menor_de_13_Años                2650 non-null   int64
 12  Dispositivo_conexión_Computadora_personal  2650 non-null   int64
 13  Dispositivo_conexión_Smartphone            2650 non-null   int64
 14  Dispositivo_conexión_Tablet                2650 non-null   int64
 15  Género_desconocido                         2650 non-null   int64
 16  Sexo_Femenino                              2650 non-null   int64
 17  Sexo_Masculino                             2650 non-null   int64
 18  Género_Otro                                2650 non-null   int64
 19  Mes                                        2650 non-null   str
 20  Año                                        2650 non-null   float64
dtypes: float64(1), int64(18), str(2)
memory usage: 434.9 KB

In [22]:
# Se borraron las columnas Rango_edad_desconocido, Autenticación_Correo, ,Autenticación_Facebook,Autenticación_Googleplus,Autenticación_Linkedin,Autenticación_Twitter, Género_desconocido
df_segmentacion.drop(columns=["Género_desconocido"], inplace=True)

KeyError: "['Género_desconocido'] not found in axis"

In [23]:
df_segmentacion.head()

,Sedes,Rango_edad_De_14_a_17_Años,Rango_edad_De_18_a_28_Años,Rango_edad_De_29_a_50_Años,Rango_edad_Mayor_de_50_Años,Rango_edad_Menor_de_13_Años,Dispositivo_conexión_Computadora_personal,Dispositivo_conexión_Smartphone,Dispositivo_conexión_Tablet,Sexo_Femenino,Sexo_Masculino,Género_Otro,Mes,Año
0,Aeroparque Juan Pablo Segundo,183,924,543,53,10,124,6988,155,835,1097,15,Julio,2018.0
1,Ampliación 1 Estación Caribe (Norte),137,884,511,36,11,242,6696,43,693,915,21,Julio,2018.0
2,Ampliación 2 Estación Caribe (Sur),111,669,347,38,18,55,6204,32,478,798,13,Julio,2018.0
3,Ampliación Estación Estadio,350,2126,1260,97,41,178,20265,107,1626,2601,39,Julio,2018.0
4,Ampliación La Honda,313,1251,474,48,27,123,9791,85,977,1216,25,Julio,2018.0

In [24]:
# Exportar el DataFrame limpio y reemplzarlo en el mismo archivo csv
df_segmentacion.to_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\segmentacion_de_usuarios.csv", index=False, encoding="utf-8", sep =",")