In [38]:
import pandas as pd

df_cantidad_usuarios = pd.read_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\cantidad_de_usuarios_por_sitio_dia.csv", encoding="utf-8", sep =",")

In [39]:
df_cantidad_usuarios.head(10)

,sede,ssid,dia_autenticación,registros,mes,año
0,aeroparque juan pablo segundo,medellin_digital,1.0,467.0,junio,2018.0
1,aeroparque juan pablo segundo,medellin_digital,2.0,672.0,junio,2018.0
2,aeroparque juan pablo segundo,medellin_digital,3.0,1085.0,junio,2018.0
3,aeroparque juan pablo segundo,medellin_digital,4.0,938.0,junio,2018.0
4,aeroparque juan pablo segundo,medellin_digital,5.0,120.0,junio,2018.0
5,aeroparque juan pablo segundo,medellin_digital,6.0,146.0,junio,2018.0
6,aeroparque juan pablo segundo,medellin_digital,7.0,502.0,junio,2018.0
7,aeroparque juan pablo segundo,medellin_digital,8.0,267.0,junio,2018.0
8,aeroparque juan pablo segundo,medellin_digital,9.0,213.0,junio,2018.0
9,aeroparque juan pablo segundo,medellin_digital,10.0,402.0,junio,2018.0

In [40]:
df_cantidad_usuarios.info()

<class 'pandas.DataFrame'>
RangeIndex: 92102 entries, 0 to 92101
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sede               92102 non-null  str
 1   ssid               91252 non-null  str
 2   dia_autenticación  91252 non-null  float64
 3   registros          91252 non-null  float64
 4   mes                91252 non-null  str
 5   año                92102 non-null  float64
dtypes: float64(3), str(3)
memory usage: 4.2 MB

In [41]:
# Se borraron las columnas ssid y dia_autenticación
df_cantidad_usuarios.drop(columns=["ssid","dia_autenticación"], inplace=True)

In [42]:
df_cantidad_usuarios.head()

                            sede  registros    mes     año
0  aeroparque juan pablo segundo      467.0  junio  2018.0
1  aeroparque juan pablo segundo      672.0  junio  2018.0
2  aeroparque juan pablo segundo     1085.0  junio  2018.0
3  aeroparque juan pablo segundo      938.0  junio  2018.0
4  aeroparque juan pablo segundo      120.0  junio  2018.0

In [ ]:
# Agrupar por mes, año y sede para obtener la cantidad total de registros por mes, año y sede
df_cantidad_usuarios=df_cantidad_usuarios.groupby(["sede","mes","año"])["registros"].agg("sum").reset_index()

In [55]:

df_cantidad_usuarios.head()

                                            sede        mes     año  registros
0                          @medellín - sapiencia       mayo  2019.0      828.0
1  \upss manrique \"\"hermenegildo de fex\"\"\""     agosto  2018.0    15275.0
2  \upss manrique \"\"hermenegildo de fex\"\"\""  diciembre  2018.0     6225.0
3  \upss manrique \"\"hermenegildo de fex\"\"\""      julio  2018.0    15495.0
4  \upss manrique \"\"hermenegildo de fex\"\"\""      junio  2018.0    19061.0

In [56]:
df_cantidad_usuarios.to_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\cantidad_de_usuarios_por_sitio_dia.csv", index=False, encoding="utf-8", sep =",")