In [2]:
import pandas as pd

df_reg_artesanos = pd.read_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\registro_artesano_y_producto_formado_y_cualificados_en_diseno.csv", encoding="utf-8", sep =",")

In [3]:
df_reg_artesanos.head()

,edad,sexo,cabeza_de_hogar,caracterizacion_ciudadano,tipo_de_emprendimiento,idea_de_negocio,estrato,barrio_vereda_ciudadano,comuna_ciudadano,zona_ciudadano,fecha_de_beneficio_dia,fecha_de_beneficio_mes,fecha_de_beneficio_año
0,63.0,masculino,si,emprendedor,artesanal,emprendedor,2.0,robledo,7,nor-occidental,15,9,2017.0
1,56.0,masculino,no,emprendedor,artesanal,emprendedor,3.0,bombona,10,centro-oriental,15,9,2017.0
2,74.0,masculino,si,emprendedor,artesanal,emprendedor,3.0,guayabal,15,sur-oriental,15,9,2017.0
3,54.0,femenino,si,emprendedor,artesanal,emprendedor,4.0,america - santa monica #2,12,centro-oriental,15,9,2017.0
4,50.0,femenino,si,emprendedor,artesanal,emprendedor,4.0,america - santa monica #2,12,centro-oriental,15,9,2017.0

In [4]:
df_reg_artesanos.info()

<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   edad                       194 non-null    float64
 1   sexo                       199 non-null    str
 2   cabeza_de_hogar            180 non-null    str
 3   caracterizacion_ciudadano  179 non-null    str
 4   tipo_de_emprendimiento     176 non-null    str
 5   idea_de_negocio            194 non-null    str
 6   estrato                    179 non-null    float64
 7   barrio_vereda_ciudadano    197 non-null    str
 8   comuna_ciudadano           197 non-null    str
 9   zona_ciudadano             197 non-null    str
 10  fecha_de_beneficio_dia     199 non-null    int64
 11  fecha_de_beneficio_mes     199 non-null    int64
 12  fecha_de_beneficio_año     199 non-null    float64
dtypes: float64(3), int64(2), str(8)
memory usage: 20.3 KB

In [ ]:
# Eliminar columnas cabeza_de_hogar, caracterizacion_ciudadano,estrato, fecha_de_beneficio_dia, fecha_de_beneficio_mes y fecha_de_beneficio_año
df_reg_artesanos.drop(columns=["cabeza_de_hogar", "caracterizacion_ciudadano", "estrato", "fecha_de_beneficio_dia", "fecha_de_beneficio_mes", "fecha_de_beneficio_año"], inplace=True)

In [7]:
df_reg_artesanos.head(20)

,edad,sexo,tipo_de_emprendimiento,idea_de_negocio,barrio_vereda_ciudadano,comuna_ciudadano,zona_ciudadano
0,63.0,masculino,artesanal,emprendedor,robledo,7,nor-occidental
1,56.0,masculino,artesanal,emprendedor,bombona,10,centro-oriental
2,74.0,masculino,artesanal,emprendedor,guayabal,15,sur-oriental
3,54.0,femenino,artesanal,emprendedor,america - santa monica #2,12,centro-oriental
4,50.0,femenino,artesanal,emprendedor,america - santa monica #2,12,centro-oriental
5,52.0,femenino,artesanal,emprendedor,san javier,13,centro-oriental
6,27.0,femenino,artesanal,emprendedor,robledo,7,nor-occidental
7,61.0,masculino,artesanal,emprendedor,campovaldes,4,nor-oriental
8,43.0,femenino,artesanal,emprendedor,doce de octubre,6,nor-occidental
9,39.0,femenino,artesanal,emprendedor,santa elena parte central,90,oriente
10,44.0,masculino,artesanal,emprendedor,manrique,3,nor-oriental
11,39.0,femenino,artesanal,emprendedor,manrique oriental,3,nor-oriental
12,59.0,masculino,artesanal,emprendedor,aranjuez,4,nor-oriental
13,53.0,femenino,artesanal,emprendedor,campovaldes,4,nor-oriental
14,41.0,femenino,artesanal,emprendedor,unidad residencial la macarena - naranjal,11,centro-oriental
15,51.0,masculino,artesanal,emprendedor,castilla,5,nor-occidental
16,56.0,femenino,artesanal,emprendedor,santa elena,90,oriente
17,36.0,masculino,artesanal,emprendedor,campovaldes,4,nor-oriental
18,54.0,masculino,artesanal,emprendedor,castilla,5,nor-occidental
19,32.0,femenino,artesanal,emprendedor,castilla,5,nor-occidental

In [9]:
df_reg_artesanos.to_csv(r"C:\Users\violeta\Documents\GitHub\MedcityHackathon\Database\registro_artesano_y_producto_formado_y_cualificados_en_diseno.csv", index=False, encoding="utf-8", sep =",")